// demos/vue/src/views/Redirect.vue
<template>
  <ion-page>
    <p>Signing in...</p>
  </ion-page>
</template>

<script lang="ts">
import { Auth } from '@/services/AuthService';
import { IonPage } from '@ionic/vue';
import {  AuthActions } from 'ionic-appauth';
import { Subscription } from 'rxjs';
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'Redirect',
    data() {
        return {
            sub: Subscription.EMPTY  
        }
    },
    created() {
        this.sub = Auth.Instance.events$.subscribe((action) => {
                if(action.action === AuthActions.SignInSuccess){
                    setInterval(() => this.$router.push('/home'), 2500)
                }
                
                if (action.action === AuthActions.SignInFailed) {
                    setInterval(() => this.$router.push('/landing'), 2500)
                }
        });

        const url = this.$route.fullPath;
        Auth.Instance.authorizationCallback(url);
    },
    beforeUnmount () {
        this.sub.unsubscribe();
    },
    components: {
        IonPage,
    }
});
</script>

// demos/react/src/pages/Redirect.tsx
import React from 'react';

import { Auth } from '../services/AuthService';
import { AuthActions } from 'ionic-appauth';
import { RouteComponentProps } from 'react-router';
import { useIonViewDidLeave, useIonViewDidEnter, IonPage } from '@ionic/react';
import { Subscription } from 'rxjs';

interface LoginRedirectPageProps extends RouteComponentProps {}

const LoginRedirect : React.FC<LoginRedirectPageProps> = (props: LoginRedirectPageProps) => {
    let sub: Subscription;
    
    useIonViewDidEnter(() => {
      let url = window.location.origin + props.location.pathname +  props.location.search;
      Auth.Instance.authorizationCallback(url);
      sub = Auth.Instance.events$.subscribe((action) => {
        if(action.action === AuthActions.SignInSuccess){
          setInterval(() => props.history.replace('home'), 2500)
        }
        
        if (action.action === AuthActions.SignInFailed) {
          setInterval(() => props.history.replace('landing'), 2500)
        }
      });
    });

    useIonViewDidLeave(() => {
      sub.unsubscribe();
    });

    return (
      <IonPage>
        <p>Signing in...</p>
      </IonPage>
    ); 
};

export default LoginRedirect;
