// demos/react/src/pages/EndRedirect.tsx
import React from 'react';

import { Auth } from '../services/AuthService';
import { RouteComponentProps } from 'react-router';
import { useIonViewWillEnter, IonPage } from '@ionic/react';

interface EndRedirectPageProps extends RouteComponentProps {
}

const EndRedirect: React.FC<EndRedirectPageProps> = (props: EndRedirectPageProps) => {

  useIonViewWillEnter(() => {
    Auth.Instance.endSessionCallback();
    setInterval(() => props.history.replace('landing'), 2500)
  });

  return (
    <IonPage>
      <p>Signing out...</p>
    </IonPage>
  );
};

export default EndRedirect;

// demos/vue/src/views/EndRedirect.vue
<template>
  <ion-page>
    <p>Signing Out...</p>
  </ion-page>
</template>

<script lang="ts">
import { Auth } from '@/services/AuthService';
import { IonPage } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'EndRedirect',
  created() {
    Auth.Instance.endSessionCallback();
    setInterval(() => this.$router.push('/landing'), 2500);
  },
  components: {
    IonPage,
  }
});
</script>
